### ISSUE TITLE
Word list

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#113]
I read through some recent mentions of plainlanguage.gov, and people seem to like this: http://www.plainlanguage.gov/howto/wordsuggestions/simplewords.cfm

Wondering if we can recreate it easily? Probably depends on #66.

**Comment by hursey013** [comment]
I remember converting that already, looks like its in `/guidelines/words/simple-words-and-phrases.md`

**Comment by nicoleslaw** [comment]
Oooh, yay! I will make some adjustments and find a good place for it.
