### ISSUE TITLE
Something something font loading

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#119]
My spouse saw me working on the prototype today and has opinions about the logo and headlines flashing on second/third/etc. page loads... Consider reducing FOIT of webfonts on page loads after the first page load? https://css-tricks.com/fout-foit-foft/

**Comment by nicoleslaw** [comment]
Seems fixed!

**Comment by hursey013** [comment]
I think this is actually still an issue, so if we have some extra hours I will follow up on it and review some of the workarounds for resolving it.
