### ISSUE TITLE
Data/front matter for examples

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#120]
I am wondering if we could add an `author` or `agency` field for front matter so these examples have some metadata. I went ahead and added it to the front matter, but am not sure what you'll think of it and am happy to revert it.

Ex: https://github.com/GSA/plainlanguage.gov/blob/master/_pages/examples/before-and-after/due-date.md

Render as: [Monthly Due Date](https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/examples/before-and-after/due-date/), Bureau of Land Management

**Comment by hursey013** [comment]
Added a check to display `author` metadata in the list layout if an author is present: https://github.com/GSA/plainlanguage.gov/commit/a3c51bb953d45ad915337a806d7bdee4f0ca96a4
