### ISSUE TITLE
Hide archival pages from list view

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#122]
/examples/handbooks/johnson-space-center-manual-example-1/
/examples/handbooks/johnson-space-center-manual-example-2/
/examples/handbooks/johnson-space-center-manual-example-3/
/examples/regulations/bureau-of-land-management/
/examples/regulations/plain-language-regulations/

**Comment by hursey013** [comment]
Added `archived` frontmatter option to hide pages from list view: https://github.com/GSA/plainlanguage.gov/commit/8a5ca6caf37d056f677a511a0f40cb49b727e880
