### ISSUE TITLE
Funky styling issues

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#123]
## Block example styling (one-column) needed

/guidelines/audience/address-the-user/
/guidelines/audience/address-separate-audiences-separately/
/guidelines/organize/make-it-easy-to-follow/
/guidelines/organize/add-useful-headings/
/guidelines/organize/use-lists/
/guidelines/organize/use-lists/#use-parallel-construction
/examples/notices/change-in-enrollment-status/
/examples/notices/failure-to-provide-claim-information/
/examples/notices/pension-medical-evidence/
/examples/regulations/minerals-management-service/
/examples/regulations/model-preamble/
/examples/handbooks/bureau-of-land-management-draft-grazing-manual/

## One-line example block quote needs styling

/guidelines/organize/add-useful-headings/

(There are more of these, but I think they're all using the normal `>` in Markdown.)

## Not sure how to solve

/examples/before-and-after/car-safety/ - maybe we could just style the text?
/design/use-tables-to-make-complex-material-easier-to-understand/
/resources/guides/ - incorporate under /law/agency-programs/ ? We talked about this a few times...

**Comment by hursey013** [comment]
Added a global style to address the block quote examples: https://github.com/GSA/plainlanguage.gov/pull/125

**Comment by hursey013** [comment]
Added standalone one-col example style: https://github.com/GSA/plainlanguage.gov/commit/a16c6094b73a4a41d42b077c2a345606900f4f76

**Comment by hursey013** [comment]
These should all be taken care of with: https://github.com/GSA/plainlanguage.gov/pull/134

The only except in the last item re: `/resources/guides/` - there are a few on there that are not Federal style guides, should those remain where they are and all of the Federal ones moved to the agency contacts page?
