### ISSUE TITLE
Car Rollover Safety Example for Before/After Image isn't legible

### ISSUE THREAD

**Issue by chriscct7** [GSA/plainlanguage.gov#157]
## Summarize the issue in one sentence
The image of the notice used in the [car rollover safety example](https://plainlanguage.gov/examples/before-and-after/car-safety/) in the before/after section isn't legible.  

A copy of this image, sized as served, is linked below:
![image](https://user-images.githubusercontent.com/1324637/32874917-280da43c-ca63-11e7-9a63-ce82474a5fc8.png)

## Tell us more about how we can help
After attempting to locate a replacement image, I believe that the best option would be to use a cropped version of the car rollover notice found in The Department of Transportation National Highway Traffic Safety Administration's Document 49 CFR Parts 571 and 575, as located at the top of page 4 as published in the US Government's Federal Register Volume 64, No. 45 from Tuesday, March 9, 1999.

This image can be found in the PDF version served from the Government Publishing Office's website here: https://www.gpo.gov/fdsys/pkg/FR-1999-03-09/pdf/99-5735.pdf#page=4.

The image, which I roughly cropped appears like such:
![image](https://user-images.githubusercontent.com/1324637/32874913-20a93aa8-ca63-11e7-98f0-9e80e0d67536.png)

Note, there is a lot of unused space in the box that is used to frame the image. Therefore, if the image is re-sourced from the above document, it does not necessarily (and perhaps for better accessibility) need to be shrunk to the same dimensions as the currently displayed image.

This image features larger text that is more legible as the image is shrunk, versus the currently displayed image (which is also from the same document; it's on the last page).

## Details

* Related links
  https://plainlanguage.gov/examples/before-and-after/car-safety/
* Operating system and version (example: Windows 10 or Mac OS X 10.12.6)
   Windows 7
* Browser and version (example: Chrome, Internet Explorer, or Safari)
  Chrome 61.0.3163.100 Official Build

**Comment by chriscct7** [comment]
As an update, by inspecting the element of the currently served image and using the raw URL to the GitHub hosted version of the cropped image above, it fits rather nicely without the need for resizing. It would be advisable however, to have someone crop to the edges of the notice and set the background outside the edges to be transparent.

Output when in place:

Before:
![image](https://user-images.githubusercontent.com/1324637/32875108-259b97bc-ca64-11e7-8721-36b97c4c0669.png)

After:
![image](https://user-images.githubusercontent.com/1324637/32875098-1d38a6d2-ca64-11e7-8464-e1c587f74d72.png)

If a larger framing is still desired it should be possible (based on quick width/height CSS checks) to do so without substantially impacting the legibility of the new image. 

This is what it would look like to retain the previous image dimensions roughly (again someone will want to redo my quick cropping work):

![image](https://user-images.githubusercontent.com/1324637/32875140-53ed86fc-ca64-11e7-9a8c-107835057a28.png)

**Comment by nicoleslaw** [comment]
@MEVincentPL Do you have any thoughts about this suggestion?

**Comment by MEVincentPL** [comment]
Not at the moment, but it's on my list for this week.

Miriam Vincent
Staff Attorney, Legal Affairs and Policy Division
Office of the Federal Register
National Archives and Records Administration
(o)202.741.6024 (bb) 202.276.3219

**Comment by nick-mon1** [comment]
Closing as this page will not be migrated.
