### ISSUE TITLE
No link previews in Facebook, Twitter, and Slack

### ISSUE THREAD

**Issue by mathowie** [GSA/plainlanguage.gov#161]
## The plain language site needs site previews added via metadata markup in the header

I was surprised when sharing the plainlanguage.gov site in Slack today to see no preview of the site or description for those about to follow the link. I viewed source and didn't find any information in the header in the form of open graph or meta description tags.

Here's a good article on how to add the least amount of header meta-information to accurately describe links for all things like Twitter, Facebook, and Slack: https://adactio.com/journal/9881 

While it would be ~5min of work to add this for the front page of the site, I would suggest sharing page title information from your CMS templates in the header tags so each preview is unique to the page being previewed on any Facebook, Twitter, or Slack message.

**Comment by hursey013** [comment]
Great feedback, and definitely an oversight on my part - will put together a pull request to implement this. Thank you!

**Comment by nicoleslaw** [comment]
Fixed in #163
