### ISSUE TITLE
Add redirect from /howto/guidelines/bigdoc/TOC.cfm to /guidelines/ ?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA/plainlanguage.gov#174]
## Summarize the issue in one sentence
OMB plain language guidance memo contains a broken link.

## Tell us more about how we can help
Adding a redirection rule from `/howto/guidelines/bigdoc/TOC.cfm` to `/guidelines/` would fix the problem.

## Details
OMB M-11-15, “Final Guidance on Implementing the Plain Writing Act of 2010”, includes this sentence:
> When drafting covered documents, your agency should follow the Federal Plain Language Guidelines available at http://www.plainlanguage.gov/howto/guidelines/bigdoc/TOC.cfm. 

Unfortunately, this link no longer works and returns a 404.

**Comment by hursey013** [comment]
Thanks for the heads up! Just added an additional redirect: https://github.com/GSA/plainlanguage.gov/pull/175
