### ISSUE TITLE
Create design pattern for before and after examples

### ISSUE THREAD

**Issue by hursey013** [GSA/plainlanguage.gov#18]
Many guidelines have inline examples which need to be distinguished from the rest of the content. Develop a wrapper for those examples, similar to the way blocks of code are typically presented.

**Comment by nicoleslaw** [comment]
- Inline examples (Don't say this, say that)
- Before and after (table/side by side)
- Longer examples

**Comment by nicoleslaw** [comment]
I am going to close this and flag any weird ones in a new issue while doing #29
