### ISSUE TITLE
Update to latest USWDS-jekyll theme

### ISSUE THREAD

**Issue by saracope** [GSA/plainlanguage.gov#262]
Currently, the site uses the [uswds-jekyll theme](https://github.com/18F/uswds-jekyll#versioning) v1.4.1 as seen in the [Gemfile](https://github.com/GSA/plainlanguage.gov/blob/master/Gemfile). That theme was recently updated and now uses the latest release of USWDS. 

Action:
* update to the latest uswds-jekyll theme
* fix any issues that arise (which is likely as this is a big USWDS jump for this project)

**Comment by nick-mon1** [comment]
Issue is stale and will be closed when site is migrated.
