### ISSUE TITLE
main.scss issues?

### ISSUE THREAD

**Issue by sharifX** [GSA/plainlanguage.gov#295]
## Summarize the issue in one sentence

I tried to copy the repo, add my own content and deploy it on my github pages. It ran locally fine but in github I ran into several issues. I was wondering if the current master branch is the correct one to use? 

After adding my own data in the config.yml, in github I got error about main.scss. 

```
Your SCSS file `assets/css/main.scss` has an error on line 2: File to import not found or unreadable: uswds/all. Load paths: _sass /hoosegow/.bundle/ruby/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-sass-or-scss.
```

I tried to change the them to uswds-jekyll but still could not get the theme to work. (I added remote_theme). 

## Tell us more about how we can help

I was wondering if could provide some input about how to re-use the nice them you have here in another site with github pages. thanks. 

## Details

* Related links
* Operating system and version (example: Windows 10 or Mac OS X 10.12.6)
* Browser and version (example: Chrome, Internet Explorer, or Safari)

**Comment by nick-mon1** [comment]
Closing because issue it stale and site will be migrated.
