### ISSUE TITLE
Create redirects

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#30]
Compare content audit with revised links, add redirects to front matter.

Relates to #29

**Comment by nicoleslaw** [comment]
Tracking progress in the spreadsheet here: https://docs.google.com/spreadsheets/d/1F1jPhLMn_KFvzaagviDMZsw355xL-xvx3mZFkzrJpX8/edit#gid=448478986

**Comment by hursey013** [comment]
Note to self: test redirect files for media files such as PDFs

**Comment by nicoleslaw** [comment]
@hursey013 These are all done except any flagged media files 🎉  Passing this issue to you.

**Comment by nicoleslaw** [comment]
Are we good to close this? We talked about maybe redirecting the main PDF and DOC links.

**Comment by hursey013** [comment]
I made a script that will copy the guideline files from the `media/` directory to the old location whenever the site is built. So the major caveat is that the names of those files will need to remain the same in order for this continue to work, future revision should be continue to be named `FederalPLGuidelines.*` - not ideal, but better than having to maintain two copies of the files in the repo. https://github.com/GSA/plainlanguage.gov/pull/143

**Comment by hursey013** [comment]
This has been merged
