### ISSUE TITLE
Change the coronavirus note to use plain language

### ISSUE THREAD

**Issue by pagibson** [GSA/plainlanguage.gov#305]
## Summarize the issue in one sentence

The coronavirus info box at the top of every page could be improved to use plain language.

## Tell us more about how we can help

Hi everybody, I really enjoy looking through this site every once in a while. I opened it up this afternoon and was tickled by the somewhat baroque language in the info box at the top of the page:

> **Information Status**
> 
> In light of OPM guidance and increasing concerns about COVID-19 (coronavirus), we are suspending accepting training requests.

Off the top of my head, it seems like the heading here should summarize the message, rather than just say "Information Status." Or maybe the heading just shouldn't exist at all, given how short the message is on its own.

There are also a few obtuse turns of phrase in here ("in light of," "suspending accepting") that I think this site would warn against! :) And I'm not sure whether the reader needs to know that the decision was made "in light of OPM guidance."

Maybe something like "Because of the COVID-19 pandemic, we are not currently accepting training requests" would suffice.

## Details

It looks like the message lives in `_config.yml`. The alert banner component is in `_includes/alert.html`.

**Comment by bonnieAcameron** [comment]
This has been resolved by https://github.com/GSA/plainlanguage.gov/pull/425.

Thank you for you contribution!
