### ISSUE TITLE
Ideas for homepage

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#36]
- [ ] Explore incorporating most recent tweet(s)
- [x] Add a callout to sign up for Events

**Comment by MEVincentPL** [comment]
We'd also like to embed a USCIS plain language video (available through youtube) that we could then change from month to month.  We didn't have this on the current site because we didn't have access to a verified 508-compliant video player

**Comment by nicoleslaw** [comment]
I added the video to https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/training/videos/. I don't recommend including tweet modules for both user experience and performance reasons. Happy to chat about that more in our next checkin.
