### ISSUE TITLE
Link to "Clarity International" does not work

### ISSUE THREAD

**Issue by lslalbai** [GSA/plainlanguage.gov#391]
## Summarize the issue in one sentence
Link to "Clarity International" does not work

## Tell us more about how we can help
Link should be updated

## Details
On [this page](https://www.plainlanguage.gov/resources/groups/) there is a link to [Clarity](http://www.clarity-international.net/) that doesn't work. [This link](https://www.clarity-international.org/) seems to be the correct one.

* Related links
* Operating system and version (example: Windows 10 or Mac OS X 10.12.6)
* Browser and version (example: Chrome, Internet Explorer, or Safari)

**Comment by lgrabuck** [comment]
Thank you for letting us know. We'll get that fixed!
