### ISSUE TITLE
Add link to USCIS videos under Resources

### ISSUE THREAD

**Issue by KatCatania** [GSA/plainlanguage.gov#53]
Hi Nicole,  Could you add a link to the USCIS Plain Language videos under Resources. The direct link is www.uscis.gov/plainlanguage.  Currently, you link to that under the Agency guides section of the new site, but the videos aren't the USCIS guide, which is only available from the USCIS internal sharepoint site so you won't be able to link to a USCIS guide on that page. 

The videos also live under uscis.gov/videos. Miriam mentioned have the functionality to rotate them ever so often on the home page. 
https://www.uscis.gov/videos/plain-language-acronyms
https://www.uscis.gov/videos/plain-language-pronouns
https://www.uscis.gov/videos/put-your-main-message-first
https://www.uscis.gov/videos/plain-language-active-voice
https://www.uscis.gov/videos/plain-language-proofreading
https://www.uscis.gov/videos/plain-language-tables
https://www.uscis.gov/videos/plain-language-bullets
https://www.uscis.gov/videos/plain-language-headings

thanks!

**Comment by nicoleslaw** [comment]
Incorporating this into issue #15
