### ISSUE TITLE
Add more info about putting your main message first

### ISSUE THREAD

**Issue by KatCatania** [GSA/plainlanguage.gov#55]
Under Writing Guidelines we need more info/example of putting your main message first. There's a brief mention of it under Organize the Information but there's no example. Maybe we can expand on that saying... For example, if you are creating web content to help someone complete a task, focus on the steps someone should take to accomplish that task. Do not begin your content explaining exceptions, related actions, or the history of your program. Remember people quickly scan the web and often leave your site if the main message is not up front. The outline of your content should look something like this:
Brief reason to read this page
Application Process/Steps
More specific information, exclusions, or disclaimers
Related information or background

There's a Digital Gov article on it. That would be great to link to or crib from. The author is one of my employees. https://www.digitalgov.gov/2016/02/12/putting-your-main-message-first/

**Comment by nick-mon1** [comment]
Closed as stale
