### ISSUE TITLE
Breakpoint on desktop

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#6]
WDS has a weird breakpoint on smaller screens that shoves the side nav below the main page. Sharing for later reference. ([Source](https://federalist-proxy.app.cloud.gov/site/gsa/plainlanguage.gov/guidelines/))

<img width="740" alt="screen shot 2017-09-11 at 9 31 24 am" src="https://user-images.githubusercontent.com/94900/30276838-152417a6-96d4-11e7-8120-d92b720973b7.png">

**Comment by hursey013** [comment]
Working on solution here: https://github.com/GSA/plainlanguage.gov/pull/52

**Comment by hursey013** [comment]
Mobile menu has been merged.
