### ISSUE TITLE
Add DAP / analytics to the site

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#61]

**Comment by hursey013** [comment]
Added DAP: https://github.com/GSA/plainlanguage.gov/commit/99d3d75a6333eacd3a9a50483a1e95773882bcfb

I think we may want Google Analytics in addition to DAP, so going to check if that is possible first before closing this.

**Comment by hursey013** [comment]
Added Google Analytics (under 18F account) as well.
