### ISSUE TITLE
Email addresses

### ISSUE THREAD

**Issue by nicoleslaw** [GSA/plainlanguage.gov#62]
- [ ] Set up info@plainlanguage.gov and training@plainlanguage.gov
- [ ] Update contact info on the site

**Comment by hursey013** [comment]
Submitted GSA IT request: REQ0324166

**Comment by hursey013** [comment]
My initial request was closed... resubmitting.

**Comment by nicoleslaw** [comment]
How are we doing on the email addresses?

**Comment by hursey013** [comment]
On hold until we take possession of the domain name. 

Relevant MX records for when DNS changes are made: https://gsa-tts.slack.com/archives/C58E45LTW/p1509461533000783

**Comment by nicoleslaw** [comment]
Fixed in #162
