### ISSUE TITLE
Get database dump from FAA

### ISSUE THREAD

**Issue by hursey013** [GSA/plainlanguage.gov#66]

**Comment by hursey013** [comment]
cc @jeremyzilar

**Comment by nicoleslaw** [comment]
Per FAA: `I’ve taken an export of the plain_lang schema of pfaagov at 4pm ET this afternoon.`

**Comment by nicoleslaw** [comment]
Still working with the FAA on this, they are waiting on a supervisor, but it sounds like they'll send a ZIP to Miriam in the next week or so.

**Comment by jeremyzilar** [comment]
I can play catcher here for this data.
